### ISSUE TITLE
Time consumption for loading results to database

### ISSUE THREAD

**Issue by CamiCit** [pyESM-project/pyesm#82]
Executing `model.load_results_to_database()` takes between 40 and 100 minutes for a model with 4 subproblems, 6 sets, 62 variables and 1345 time steps.

In `core.cvxpy_endogenous_data_to_database()`, the bottleneck is in `sqltools.dataframe_to_table()`. 
If this method is bypassed (and endogenous variables are exported as .csv files) it takes only around 10 seconds.

**Comment by Mast86** [comment]
The problem seems to be linked with the operation=='update' argument. indeed, the 'update' mode runs the sql UPDATE query, that is significantly lower compared to operation=='overwrite'.
i feel the overall 'update' logic should be revised: how the method is behaving in case the new data are only partially overlapped compared to the existing data? what if there are existing data that are not present in the new data? the whole method should be revise. meanwhile, i set the default argument operation == 'overwrite' in model.load_results_to_database().

**Comment by Mast86** [comment]
This issue should be solved with the last update in dev_model. I ask @CamiCit to fetch dev_model branch and to test this version against your case to check the speed of data export to database. 
Pay attention: the arguments of the main methods have been slightly changed (operation argument has deprecated).
Let me know if the timing has improved.
